<?php
	if (!empty($wo['story']['product_id'])) {
		$class = '';
		$small = '';
		$singleimg = '';
		if (count($wo['story']['product']['images']) == 1) {
			$singleimg = 'wo_single_proimg';
		}
		if (count($wo['story']['product']['images']) == 2) {
            $class = 'width-2';
		}
		if (count($wo['story']['product']['images']) > 1) {
            $small = '_small';
		}
		if (count($wo['story']['product']['images']) > 2) {
            $class = 'width-3';
		}
		if (count($wo['story']['product']['images']) > 3) {
			foreach (array_slice($wo['story']['product']['images'],0,3) as $key => $photo) {
				if ($key == 2) {
					echo "<div onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");' class='album-collapse pointer'>
                       <img src='".($photo['image_org'])."' class='image-file'>
                       <span>+".count(array_slice($wo['story']['product']['images'],2))."</span>
                   </div>
                   "; 
				}
				else{
					echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                  onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
				}
			}
			foreach (array_slice($wo['story']['product']['images'],3) as $photo) {
				echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
                 onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
			}
		}
		else{ 
			foreach ($wo['story']['product']['images'] as $photo) {
				echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " " . $singleimg . " image-file pointer'
                 onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
			}
		}
		echo '<br><br>';
		$symbol =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['symbol'])) ? $wo['currencies'][$wo['story']['product']['currency']]['symbol'] : $wo['config']['classified_currency_s'];
		$text =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['text'])) ? $wo['currencies'][$wo['story']['product']['currency']]['text'] : $wo['config']['classified_currency'];
		echo '<div class="wow_post_prod">';
		echo '<h4 class="wow_post_prod_name">' . $wo['story']['product']['name'] . '</h4>';
		echo '<div class="wow_post_prod_shead">';
		if (!empty($wo['story']['product']['location'])) {
			echo '<span> ' . $wo['story']['product']['location'] . '</span><span class="middot">·</span>';
		}
		echo '</div>';

		echo '<div style="display:none;width: 100p%;height: 70px;background-color: black;border-radius: 10px;padding-top: 10px" align="center" id="timer">
		<p id="demo" style="font-size: 32px;color: white;"></p></div>
		<div class="row"> <div class="wow_post_prod_infos "><svg style="float:left; margin-right:10px;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description product-description-'.$wo['story']['product']['id'].'">' . $wo['story']['product']['description'] . '</p></div></div>';

		echo'<div class="row"> ';
		echo '<div align="center"class="wow_post_prod_infos col-md-4"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><b>' . $wo['lang']['category'] . '</b><p class="product-description product-description-'.$wo['story']['product']['id'].'"><b>' . $wo['story']['product']['category'] . '</b></p></div>';
        echo '<div align="center" class="wow_post_prod_infos col-md-4"><b>' . $wo['lang']['price'] . '</b></br> <span class="product-description" style="max-height: none;">' . $symbol . $wo['story']['product']['price'] . ' (' . $text . ')</span></div>';
		 echo '<div align="center"class="wow_post_prod_infos col-md-4"><b>' . $wo['lang']['phase_one'] . ' </b><span class="product-description" style="max-height: none;"><b>Countdown</b><br>24 Hours</span></div>';
        echo'</div>';
		$fields = Wo_GetCustomFields('product'); 
		if (!empty($fields)) {
			foreach ($fields as $key => $wo['field']) { 
				if (!empty($wo['story']['product']['fid_'.$wo['field']['id']])) {
					if ($wo['field']['type'] == 'selectbox') {
						$options = @explode(',', $wo['field']['options']);
						foreach ($options as $key => $value) {
							if (($key + 1) == $wo['story']['product']['fid_'.$wo['field']['id']]) {
								$wo['story']['product']['fid_'.$wo['field']['id']] = $value;
							}
						}
					}
					echo '<div class="wow_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description">' . $wo['story']['product']['fid_'.$wo['field']['id']] . '</p></div>';
		        } 
		    } 
	    }
		echo '</div>';
		if ($wo['loggedin']) {
		if ($wo['page']  == 'story' && $wo['story']['product']['user_id'] != $wo['user']['user_id'])
		 { ?>
			<br>
			<button class="contact btn btn-success btn-mat" onclick="Wo_OpenChatTab(<?php echo $wo['story']['product']['user_id']?>,0,<?php echo $wo['story']['product']['id']?>)"><?php echo $wo['lang']['contact_seller'] ?></button>
            <button class="contact btn btn-success " onclick="Accept_Challange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)"><?php echo $wo['lang']['accept_challange'] ?></button>
 <button class="contact btn btn-success win" style="display:none;" onclick="WinChallange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)">Win</button>
 <button class="contact btn btn-danger win"style="display:none;">Loose</button>
 <button class="contact btn btn-danger win"style="display:none;">Dispute</button>
<?php
$check= Check_Challange($wo['story']['product']['id']);
if($check=='exist'){
?>
 <button class="contact btn btn-success" onclick="WinChallange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)">Win</button>
 <button class="contact btn btn-danger" onclick="LooseChallange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)">Loose</button>
<button class="contact btn btn-danger" onclick="DisputeChallange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)">Dispute</button>
<?php
}
?>
<?php
			}
			}
	} 
?>
<div id="razorpay_alert"></div>

            <script>
            function Wo_OpenAlbumLightBoxChallange(image_id, type) {
  $('body').append('<div class="lightbox-container"><div class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div><div class="lb-preloader" style="display:block"><svg width="50px" height="50px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"><rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect><circle cx="50" cy="50" r="40" stroke="#676d76" fill="none" stroke-width="6" stroke-linecap="round"><animate attributeName="stroke-dashoffset" dur="1.5s" repeatCount="indefinite" from="0" to="502"></animate><animate attributeName="stroke-dasharray" dur="1.5s" repeatCount="indefinite" values="150.6 100.4;1 250;150.6 100.4"></animate></circle></svg></div></div>');
  $.get(Wo_Ajax_Requests_File(), {f:'open_album_lightbox_challange', image_id:image_id, type:type}, function(data) {
    if (data.status == 200) {
      document.body.style.overflow = 'hidden';
      $('.lightbox-container').html(data.html);
    }
    if (data.html.length == 0) {
      document.body.style.overflow = 'auto';
    }
  });
}
            function Accept_Challange(acceptor,creator,challange) {

             $.get(Wo_Ajax_Requests_File(), {f:'accept_challange', acceptor_id:acceptor, creator_id:creator,challange_id:challange}, function(data) {
                 if (data.status == 200) {
                     if(data.message=='no_wallet'){
                         $('#razorpay_alert').html("<div class='alert alert-danger'>Creator Have No Limit to Proceed This Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }
                     else if(data.message=='already_challange'){
                         $('#razorpay_alert').html("<div class='alert alert-danger'>You Have already Created the Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }

                     else if(data.message=='accepted'){
                         $('.win').show();
                         $('#timer').show();
                         $('#razorpay_alert').html("<div class='alert alert-success'>Challange Accepted</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                    var countDownDate = new Date();
            countDownDate.setDate(countDownDate.getHours() + 7);

            // Update the count down every 1 second
            var x = setInterval(function() {

              // Get today's date and time
              var now = new Date().getTime();

              // Find the distance between now and the count down date
              var distance = countDownDate - now;

              // Time calculations for days, hours, minutes and seconds
              var days = Math.floor(distance / (1000 * 60 * 60 * 24));
              var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
              var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
              var seconds = Math.floor((distance % (1000 * 60)) / 1000);

              // Output the result in an element with id="demo"
              document.getElementById("demo").innerHTML = days + "d " + hours + "h "
              + minutes + "m " + seconds + "s ";
              // If the count down is over, write some text
              if (distance < 0) {
                clearInterval(x);
                document.getElementById("demo").innerHTML = "EXPIRED";
              }
            }, 1000);
                     }
                      else if(data.message=='challange_limit_reach'){
                         $('#razorpay_alert').html("<div class='alert alert-danger'>Sorry You Can't Accept Challange. Limit Reached</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }
                     else{
                         $('#razorpay_alert').html("<div class='alert alert-danger'>Some Error</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }

                }
              });
            }
            function WinChallange(acceptor,creator,challange) {

             $.get(Wo_Ajax_Requests_File(), {f:'win_challange', acceptor_id:acceptor, creator_id:creator,challange_id:challange}, function(data) {
                 if (data.status == 200) {
                     if(data.message=='winner'){
                         $('#razorpay_alert').html("<div class='alert alert-success'>Congratulation You Won This Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }
                     if(data.message=='playing'){
                         $('#razorpay_alert').html("<div class='alert alert-success'>Challenge is Playing</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }
                     if(data.message=='played'){
                         $('#razorpay_alert').html("<div class='alert alert-danger'>You Already Played This Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }


                 }
                 });
            }
            function LooseChallange(acceptor,creator,challange) {

             $.get(Wo_Ajax_Requests_File(), {f:'loose_challange', acceptor_id:acceptor, creator_id:creator,challange_id:challange}, function(data) {
                 if (data.status == 200) {
                     if(data.message=='loose'){
                         $('#razorpay_alert').html("<div class='alert alert-success'>Sorry You Loose This Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }
                      if(data.message=='playing'){
                         $('#razorpay_alert').html("<div class='alert alert-success'>Challenge is Playing</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }

                     if(data.message=='played'){
                         $('#razorpay_alert').html("<div class='alert alert-danger'>You Already Played This Challenge</div>");
                    setTimeout(function () {
                        $('#razorpay_alert').html("");
                    },3000);
                     }


                 }
                 });
            }
            function DisputeChallange(acceptor,creator,challange) {
 $.get(Wo_Ajax_Requests_File(), {f:'dispute_challange', acceptor_id:acceptor, creator_id:creator,challange_id:challange}, function(data) {
     if (data.status == 200) {

          if(data.message=='dispute'){
             $('#razorpay_alert').html("<div class='alert alert-success'>You Successfully Disputed The Challange</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
         }
         if(data.message=='played'){
             $('#razorpay_alert').html("<div class='alert alert-danger'>You Already Played This Challenge</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
         }
     }
     });
}
</script>