<div class="container-fluid">
    <div class="block-header">
        <h2>Arena > Arena Challagnes</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
<div class="col-lg-12 col-md-12">
  <div class="card">
      <div class="header">
          <h2>Arena > Arena Challagnes</h2>
      </div>
      <div class="body">
          <div class="row">

            <div class="col-md-4" style="margin-bottom:0;">

            </div>
          </div>
          <div class="clearfix"></div>
          <div class="table-responsive1">
              <table class="table table-bordered table-striped table-hover">
                  <thead>
                  <tr>
                               <th>ID</th>
                              <th>User Name</th>
                              <th>Win Point</th>
                              <th>Loose Point</th>
                              <th>Gifted</th>
                  </tr>
                  </thead>
                   <tbody>
<?php
foreach (Challanges_point() as $wo['createdleadlist']) {
    ?>
    <tr><td><?php echo $wo['createdleadlist']['id']?></td>
    <td><?php echo $wo['createdleadlist']['username']?></td>
    <td><?php echo  $wo['createdleadlist']['win_point']?></td>
    <td><?php echo $wo['createdleadlist']['loose_point']?></td>
    <td><?php echo $wo['createdleadlist']['gift_point']?></td></tr>
    <?php
}
?>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
</div>
</div>