<tr class="user-list" id="UserID_<?php echo $wo['createdleadlist']['id']?>"
    data-user-id="<?php echo $wo['createdleadlist']['id']?>">
    <td><?php echo $wo['createdleadlist']['id']?></td>
    <td><?php echo $wo['createdleadlist']['username']?></td>
    <td><?php echo  $wo['createdleadlist']['win_point']?></td>
    <td><?php echo $wo['createdleadlist']['loose_point']?></td>
    <td><?php echo $wo['createdleadlist']['gift_point']?></td>
</tr>