<tr class="user-list" id="UserID_<?php echo $wo['createdleadlist']['id']?>"
    data-user-id="<?php echo $wo['createdleadlist']['id']?>">
    <td><?php echo $wo['createdleadlist']['id']?></td>
    <td><?php echo $wo['createdleadlist']['username']?></td>
    <td><?php echo $wo['createdleadlist']['name']?></td>
    <td><?php echo $wo['createdleadlist']['price']?></td>
    <td><?php echo $wo['createdleadlist']['category']?></td>
    <td><?php echo $wo['createdleadlist']['description']?></td>

</tr>