<div class="product col-proxs-12 col-xs-6 col-sm-4 col-md-4" id="product-<?php echo $wo['product']['id']?>" data-id="<?php echo $wo['product']['id']?>">
	<div class="product_info wow_main_mkt_prod">
		<div class="product-image">
			<a href="<?php echo $wo['product']['url']?>"data-ajax="?link1=challange&id=<?php echo $wo['product']['post_id'];?>" >
			<img src="<?php echo $wo['product']['images'][0]['image_org'];?>">
			</a>
<?php if ($wo['loggedin']) { if ($wo['product']['seller']['id'] != $wo['user']['user_id']) { ?>
    <div class="product-links">
        <a class="more-info btn btn-mat" href="<?php echo $wo['product']['url']?>"data-ajax="?link1=challange&id=<?php echo $wo['product']['post_id'];?>"  >
<?php echo $wo['lang']['more_info'] ?>
</a>
    </div>
<?php } else { ?>
<?php } ?>
<?php } ?>
</div>
<div class="produc_info">
<div class="product-title">
<a href="<?php echo $wo['product']['url']?>" data-ajax="?link1=challange&id=<?php echo $wo['product']['post_id'];?>"  title="<?php echo $wo['product']['name']?>"><?php echo $wo['product']['name']?></a>
</div>
<div class="product-price">
<?php echo (!empty($wo['currencies'][$wo['product']['currency']]['symbol'])) ? $wo['currencies'][$wo['product']['currency']]['symbol'] : $wo['config']['classified_currency_s'];?><?php echo $wo['product']['price']?>
</div>
</div>
<div class="wow_main_prod_foot">
<?php if ($wo['loggedin']) { if ($wo['product']['seller']['id'] != $wo['user']['user_id']) { ?>
    <button class="contact btn btn-success btn-mat" onclick="Wo_OpenChatTab(<?php echo $wo['product']['seller']['id']?>,0,<?php echo $wo['product']['id']?>)"><?php echo $wo['lang']['contact_seller'] ?></button>
<?php } else { ?>
    <a class="btn btn-success btn-mat" href="<?php echo $wo['product']['url']?>" data-ajax="?link1=challange&id=<?php echo $wo['product']['post_id'];?>" ><?php echo $wo['lang']['more_info'] ?></a>
<?php } ?>
<?php } ?>
</div>
</div>
<div class="clear"></div>
</div>