<?php
	if (!empty($wo['story']['product_id'])) {
		$class = '';
		$small = '';
		$singleimg = '';
		if (count($wo['story']['product']['images']) == 1) {
			$singleimg = 'wo_single_proimg';
		}
		if (count($wo['story']['product']['images']) == 2) {
            $class = 'width-2';
		}
		if (count($wo['story']['product']['images']) > 1) {
            $small = '_small';
		}
		if (count($wo['story']['product']['images']) > 2) {
            $class = 'width-3';
		}
		if (count($wo['story']['product']['images']) > 3) {
			foreach (array_slice($wo['story']['product']['images'],0,3) as $key => $photo) {
				if ($key == 2) {
					echo "<div onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");' class='album-collapse pointer'>
                       <img src='".($photo['image_org'])."' class='image-file'>
                       <span>+".count(array_slice($wo['story']['product']['images'],2))."</span>
                   </div>
                   "; 
				}
				else{
					echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                  onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
				}
			}
			foreach (array_slice($wo['story']['product']['images'],3) as $photo) {
				echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
                 onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
			}
		}
		else{
			foreach ($wo['story']['product']['images'] as $photo) {
				echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " " . $singleimg . " image-file pointer' 
                 onclick='Wo_OpenAlbumLightBoxChallange(" . $photo['id'] . ", \"product\");'>";
			}
		}
		echo '<br><br>';
		$symbol =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['symbol'])) ? $wo['currencies'][$wo['story']['product']['currency']]['symbol'] : $wo['config']['classified_currency_s'];
		$text =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['text'])) ? $wo['currencies'][$wo['story']['product']['currency']]['text'] : $wo['config']['classified_currency'];
		echo '<div class="wow_post_prod">';
		echo '<h4 class="wow_post_prod_name">' . $wo['story']['product']['name'] . '</h4>';
		echo '<div class="wow_post_prod_shead">';
		if (!empty($wo['story']['product']['location'])) {
			echo '<span> ' . $wo['story']['product']['location'] . '</span><span class="middot">·</span>';
		}
		echo '</div>';
		echo '<div class="wow_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,8H4V6H20M20,18H4V12H20M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg>' . $wo['lang']['price'] . ' <span class="product-description" style="max-height: none;">' . $symbol . $wo['story']['product']['price'] . ' (' . $text . ')</span></div>';
		echo '<div class="wow_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description product-description-'.$wo['story']['product']['id'].'">' . $wo['story']['product']['description'] . '</p></div>';


		$fields = Wo_GetCustomFields('product'); 
		if (!empty($fields)) {
			foreach ($fields as $key => $wo['field']) { 
				if (!empty($wo['story']['product']['fid_'.$wo['field']['id']])) {
					if ($wo['field']['type'] == 'selectbox') {
						$options = @explode(',', $wo['field']['options']);
						foreach ($options as $key => $value) {
							if (($key + 1) == $wo['story']['product']['fid_'.$wo['field']['id']]) {
								$wo['story']['product']['fid_'.$wo['field']['id']] = $value;
							}
						}
					}
					echo '<div class="wow_post_prod_infos"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg><p class="product-description">' . $wo['story']['product']['fid_'.$wo['field']['id']] . '</p></div>';
		        } 
		    } 
	    }
		echo '</div>';
		if ($wo['loggedin']) {
		if ($wo['page']  == 'story' && $wo['story']['product']['user_id'] != $wo['user']['user_id'])
		 { ?>
			<br>
			<button class="contact btn btn-success btn-mat" onclick="Wo_OpenChatTab(<?php echo $wo['story']['product']['user_id']?>,0,<?php echo $wo['story']['product']['id']?>)"><?php echo $wo['lang']['contact_seller'] ?></button>
            <button class="contact btn btn-success " onclick="Accept_Challange(<?php echo $wo['user']['user_id']?>,<?php echo $wo['story']['product']['user_id']?>,<?php echo $wo['story']['product']['id']?>)"><?php echo $wo['lang']['accept_challange'] ?></button>
			<?php
			}
			}
	} 
?>
<div id="razorpay_alert"></div>
<p id="demo"></p>
            <script>
            function Wo_OpenAlbumLightBoxChallange(image_id, type) {
  $('body').append('<div class="lightbox-container"><div class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div><div class="lb-preloader" style="display:block"><svg width="50px" height="50px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"><rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect><circle cx="50" cy="50" r="40" stroke="#676d76" fill="none" stroke-width="6" stroke-linecap="round"><animate attributeName="stroke-dashoffset" dur="1.5s" repeatCount="indefinite" from="0" to="502"></animate><animate attributeName="stroke-dasharray" dur="1.5s" repeatCount="indefinite" values="150.6 100.4;1 250;150.6 100.4"></animate></circle></svg></div></div>');
  $.get(Wo_Ajax_Requests_File(), {f:'open_album_lightbox_challange', image_id:image_id, type:type}, function(data) {
    if (data.status == 200) {
      document.body.style.overflow = 'hidden';
      $('.lightbox-container').html(data.html);
    }
    if (data.html.length == 0) {
      document.body.style.overflow = 'auto';
    }
  });
}

function Accept_Challange(acceptor,creator,challange) {

 $.get(Wo_Ajax_Requests_File(), {f:'accept_challange', acceptor_id:acceptor, creator_id:creator,challange_id:challange}, function(data) {
     if (data.status == 200) {
         if(data.message=='no_wallet'){
             $('#razorpay_alert').html("<div class='alert alert-danger'>Creator Have No Limit to Proceed This Challenge</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
         }
         else if(data.message=='accepted'){
             $('#razorpay_alert').html("<div class='alert alert-success'>Challange Accepted</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
		var countDownDate = new Date();
countDownDate.setDate(countDownDate.getHours() + 7);

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";
  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
         }
          else if(data.message=='challange_limit_reach'){
             $('#razorpay_alert').html("<div class='alert alert-danger'>Sorry You Can't Accept Challange. Limit Reached</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
         }
         else{
             $('#razorpay_alert').html("<div class='alert alert-danger'>Some Error</div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
         }

    }
  });
}

</script>